//-----------------------------------------------------------------------------
// pages/index.tsx
//-----------------------------------------------------------------------------
import type { 
  NextPage,
  GetStaticProps,
}                         from 'next'
import Head               from 'next/head'
import Image              from 'next/image'
import Link               from 'next/link'

import { 
  getSortedPostsData, 
}                         from '../lib/posts'
import { 
  IBlogPost,
}                         from '../interfaces/blog.interfaces'
import Layout             from '../components/layout'
import Date               from '../components/date'
import styles             from '../styles/Home.module.css'

/**
 * @function getStaticProps
 * @returns  An array of all the blog post data as properties for the Home component
 */
 export const getStaticProps: GetStaticProps = async () => {
  const  allPostsData = getSortedPostsData()
  return {
    props: {
      allPostsData
    }
  }
}

/**
 * @function  Home
 * @returns 
 */
export default function Home({ allPostsData }: { allPostsData: IBlogPost[] }) {
  return (
    <Layout>
      <div className={styles.container}>
        <Head>
          <title>Mike Daley Website</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <div>
          <h2>Dude, Blog Posts</h2>
          <ul>
            {allPostsData.map( ({id, title, date}) => {
              return (
                <li key={id}>
                  <Link href={`/posts/${id}`}>
                    <a>{title}</a>
                  </Link>
                  <br />
                  <small>
                    <Date dateString={date} />
                  </small>
                </li>
              )
            })}
          </ul>
        </div>

        <main className={styles.main}>
          <h1 className={styles.title}>
            Welcome to <a href="https://nextjs.org">Next.js!</a>
          </h1>

          <p className={styles.description}>
            Get started by editing{' '}
            <code className={styles.code}>pages/index.tsx</code>
          </p>

          <div className={styles.grid}>
            <a href="https://nextjs.org/docs" className={styles.card}>
              <h2>Documentation &rarr;</h2>
              <p>Find in-depth information about Next.js features and API.</p>
            </a>

            <a href="https://nextjs.org/learn" className={styles.card}>
              <h2>Learn &rarr;</h2>
              <p>Learn about Next.js in an interactive course with quizzes!</p>
            </a>

            <a
              href="https://github.com/vercel/next.js/tree/master/examples"
              className={styles.card}
            >
              <h2>Examples &rarr;</h2>
              <p>Discover and deploy boilerplate example Next.js projects.</p>
            </a>

            <a
              href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              className={styles.card}
            >
              <h2>Deploy &rarr;</h2>
              <p>
                Instantly deploy your Next.js site to a public URL with Vercel.
              </p>
            </a>
          </div>
        </main>

        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{' '}
            <span className={styles.logo}>
              <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            </span>
          </a>
        </footer>
      </div>
    </Layout>
  )
}

